# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ParseForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 900)
        Form.setStyleSheet("background-color: rgb(42, 93, 120);")
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 800, 330))
        self.listWidget.setStyleSheet("color: rgba(161, 217, 247,97);\n"
"border-radius: 10px;\n"
"border: 2px solid black;\n"
"padding: 0 0 0 10px")
        self.listWidget.setObjectName("listWidget")
        self.listWidget.setWordWrap(True)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(0, 350, 811, 471))
        self.textEdit.toPlainText().encode("utf-8")
        self.textEdit.setStyleSheet("color: rgba(161, 217, 247,97);\n"
"border-radius: 10px;\n"
"border: 2px solid black")
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(160, 840, 491, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        font_textedit = QtGui.QFont()
        font_textedit.setPointSize(11)
        self.listWidget.setFont(font)
        self.textEdit.setFont(font_textedit)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(128, 172, 196);\n"
"color: rgb(42, 93, 120);\n"
"border-radius: 20px;")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Показать"))
